### ISSUE TITLE
Public: Change "Named Subject" field to "Names"

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/ursus#102]
Acceptance Criteria:
- The named_subject field is called "Names" in:
  - [x] Facet sidebar
  - [x] Single-item display

**Comment by hardyoyo** [comment]
facet sidebar:
![image](https://user-images.githubusercontent.com/611569/48145434-7283e700-e278-11e8-8ae4-8088894c59b1.png)

**Comment by hardyoyo** [comment]
single item display on ursus-test:
![image](https://user-images.githubusercontent.com/611569/48145583-b7a81900-e278-11e8-9657-abf7f81fde01.png)
