### ISSUE TITLE
Public: Enable serving compressed assets to speed page load time

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#116]
**STORY**
As a systems owner, I'd like to configure apache to serve the gzipped version of assets that are created during deployment of **URSUS**, so that end users get faster page loads.

**DETAILS**
For an overview, see the [Asset Pipeline Rails Guide](https://guides.rubyonrails.org/asset_pipeline.html), especially the gzip section of [Custoimizing the Pipeline](https://guides.rubyonrails.org/asset_pipeline.html#customizing-the-pipeline)

Additional info specific to Apache configuration can be found here:  
* https://coderwall.com/p/sx-8xa/serving-pre-compressed-assets-through-apache
* https://stackoverflow.com/questions/7509501/how-to-configure-mod-deflate-to-serve-gzipped-assets-prepared-with-assetsprecom/7510773#7510773

**ACCEPTANCE**
- [ ] gzipped versions of assets are created during deployment
- [x] The Apache server for **URSUS** is configured to serve the compressed versions of assets
  - [x] VM environment (embark)
  - [x] development environment
  - [x] test environment
  - [x] staging environment
  - [ ] production environment

**Comment by hardyoyo** [comment]
I've done similar work for DSpace, I can tackle this, as soon as we put it in a sprint

**Comment by hardyoyo** [comment]
here is the Apache config file which will need to have the mod_deflate config lines added:
https://github.com/UCLALibrary/uclalib_role_blacklight_capdeploy/blob/master/templates/apache_vhost.j2

**Comment by hardyoyo** [comment]
Manually tested these configuration lines in vagrant-emark:

```
# See story #116, Set to gzip all output
LoadModule deflate_module modules/mod_deflate.so
SetOutputFilter DEFLATE

#exclude the following file types
SetEnvIfNoCase Request_URI \.(?:exe|t?gz|zip|iso|tar|bz2|sit|rar|flv|swf|mp3)$ no-gzip dont-vary

#set compression level
DeflateCompressionLevel 9

#Handle browser specific compression requirements
BrowserMatch ^Mozilla/4 gzip-only-text/html
BrowserMatch ^Mozilla/4.0[678] no-gzip
BrowserMatch bMSIE !no-gzip !gzip-only-text/html
SetEnvIf User-Agent ".*MSIE.*" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
```
Confirmed via [Chrome Dev Tools](https://webmasters.stackexchange.com/questions/4607/is-there-an-easy-way-to-see-amount-of-compression-in-chrome) that compression is on, and working for JS, CSS, PNG and JPEG files. This compression should not affect images served by our Cantaloupe/IIIF server.

I will work on a revision of the Ansible role responsible for this config.

**Comment by hardyoyo** [comment]
pull request: https://github.com/UCLALibrary/uclalib_role_blacklight_capdeploy/pull/2

**Comment by hardyoyo** [comment]
`curl -ksH 'Accept-encoding: gzip' https://ursus-stage.library.ucla.edu/ | gunzip -t -` (same for -dev and -test) proves that gzip compression is on for all three environments, and if you use Chrome devtools, you'll see that JS, HTML and CSS are being compressed.
![image](https://user-images.githubusercontent.com/611569/48288588-44e29d80-e432-11e8-827c-7c5065376151.png)

**Comment by hardyoyo** [comment]
two checkboxes in the acceptance are unclear: we don't have a production environment, and do we really need to create compressed assets?

**Comment by mark-dce** [comment]
This is awesome.  

The first checkbox should be a no-action necessary - I put it there so someone would confirm that the necessary compressed assets are being created when we deploy (because Capistrano should be running rake assets:precompile).  I.E. I think we want to make sure the assets are being compressed once at deployment time, not dynamically on request.

The `production` checkbox was because I couldn't know if the "Build Production" or this ticket would be done first.  As long as you've coordinated with Stephen so the production web server gets built using the appropriate scripts, I'm happy if you want to check it off here or mark it as ~moot~.
