### ISSUE TITLE
Public: handle sass gem deprecation

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#118]
**ISSUE**
The `sass` gem currently used by the application will go end-of-life on 26 March 2019.

**DETAILS**
A thorough upgrade guide for upgrading to the `sash-rails` gem can be found here; http://sass.logdown.com/posts/7081811

**ACCEPTANCE**
- [ ] **URSUS** no longer depends on the `sass` gem (i.e. it no longer show up in `Gemfile.lock`)

Depends on https://github.com/UCLALibrary/californica/issues/321

**Comment by hardyoyo** [comment]
[PR 128](https://github.com/UCLALibrary/ursus/pull/128) broke our deployment, due to font-awesome missing from the sassc gem. Californica had a similar issue, and [PR332](https://github.com/UCLALibrary/californica/pull/332) resolved it. We should port those changes to Ursus. Reopening this.
