### ISSUE TITLE
Featured item caption should take me to the item

### ISSUE THREAD

**Issue by RachelDCE** [UCLALibrary/ursus#124]
**ACCEPTANCE**
- [x] When I click on the caption I should go to the page for that image instead of a list of images

**Comment by val99erie** [comment]
@mark-dce Could you please clarify:  Clicking the caption should go to the individual record, but what about clicking the image?  Still go to the individual record?  Or go to the search page?

**Comment by mark-dce** [comment]
Only the caption link behavior should be changed.  Clicking anywhere on the image should continue take you to the facet results for the corresponding subject keyword like it does right now.
