### ISSUE TITLE
Public: define citation format

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#125]
**STORY**
As a student scholar, I would like ursus to provide me proper citation information when I reference a work in the digital library.

**OPTIONS**
- OPTION 1 - Link to a static citation guide - e.g. "To Cite:" link in [Tufts Digital Library work](https://dl.tufts.edu/catalog/tufts:MS001.022.001.00008.00003)  
- OPTION 2 - Dynamically generate a citation - e.g. "Cite" link in [Project Blacklight Demo](https://demo.projectblacklight.org/catalog/2008002981) or [Cornell University Special Collections](https://lindquist.cul.columbia.edu/catalog/burke_lindq_035_0053) *NOTE: if choosing this option, please provide both a complete example of the desired citation text for a sample item in the collection, along with the general formatting and citation instructions*  
- OPTION 3 - Remove the citation link until a future phase (matched current DLCS behavior)

**ACCEPTANCE**
- [x] Identify selected option
- [x] Provide example citation information
- [x] Update #73 correspondingly

**NOTES**
To implement OPTION 3, see https://github.com/projectblacklight/blacklight/wiki/Adding-new-document-actions#removing-actions.

**Comment by sshaferUCLA** [comment]
Request for feedback has been sent to Samvera Users Group (SUG). Feedback/discussions are being collected on https://docs.library.ucla.edu/x/ZSzcCg
Feedback due date is Nov 14
Results of feedback and discussions will be submitted to this ticket.

**Comment by sshaferUCLA** [comment]
So far - one vote from Samvera Users Group:  
I like option 2. with an option of choosing a specific style and email citation to users

**Comment by mark-dce** [comment]
We won't necessarily know the user's e-mail so the typical behavior is to provide text that can be cut and pasted into a word processor.  

If we need other behavior like a link to download information for a citation manager like EndNote or Mendely or to have a citation e-mailed, we should write these up as separate individual stories.

We'll need a few examples of proper citations that we can use to set up the proper formatting for option 2

**Comment by sshaferUCLA** [comment]
SUG likes option 2 with the following format for a citation:

Example record for citation model
 https://ursus-stage.library.ucla.edu/catalog/kw52j814x#?c=&m=&s=&cv=&xywh=-859%2C-1%2C7916%2C4931 

Citation format
Frank E. Walker, father of murder victim Frances Walker, sits in a crowded room, Los Angeles, 1935. [still image]. Los Angeles Daily News Negatives. UCLA Library Distinctive Digital Collections. https://ursus-stage.library.ucla.edu/catalog/kw52j814x#?c=&m=&s=&cv=&xywh=-859%2C-1%2C7916%2C4931 (web accessed 14 November 2018)

SUG wants the accessed date to be automatically generated.

**Comment by emcaulay** [comment]
@mark-dce , please comment on the effectiveness of the following generic format. 

Curly brackets {} indicate data to be extracted from Samvera, value inside square brackets is the field name from Samvera. 
+ indicates system to generate+
All other characters are literals.

{title}. [still image]. {collection name}. UCLA Library Distinctive Digital Collections. {persistent URL here} (web accessed +DD MONTH YYYY+)

**Comment by emcaulay** [comment]
I have just re-read the acceptance criteria, and now realize I don't need Mark's review on this ticket. I just need to bop over and update #73.
