### ISSUE TITLE
Public: Replace `--` with em dash

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/ursus#129]
Related to https://github.com/UCLALibrary/ursus/issues/101
Related to https://github.com/UCLALibrary/californica/issues/316

Subject headings in the DLCS export csv contain many dashes rendered as two hyphens. Not only does this look bad in itself, it also causes the browser to break lines at inferior locations:
<img width="271" alt="screen shot 2018-11-06 at 9 34 04 am" src="https://user-images.githubusercontent.com/73365/48083512-2ff3d900-e1aa-11e8-8168-91ccea389ee4.png">

Acceptance criteria:

- [ ] Ursus converts double hyphens (`--`) in the solr index to em dashes (`—`, U+2014):
<img width="272" alt="screen shot 2018-11-06 at 9 33 09 am" src="https://user-images.githubusercontent.com/73365/48083536-3f732200-e1aa-11e8-9dca-8d743d48a62a.png">

We could also consider spaces and en dashes, which results in slightly different line breaks:
<img width="272" alt="screen shot 2018-11-06 at 9 31 15 am" src="https://user-images.githubusercontent.com/73365/48083569-5c0f5a00-e1aa-11e8-941a-533155ac94d0.png">

**Comment by andrewbenedictwallace** [comment]
Related to https://github.com/UCLALibrary/ursus/issues/101
Related to https://github.com/UCLALibrary/californica/issues/316

Subject headings in the DLCS export csv contain many dashes rendered as two hyphens. Not only does this look bad in itself, it also causes the browser to break lines at inferior locations:
<img width="271" alt="screen shot 2018-11-06 at 9 34 04 am" src="https://user-images.githubusercontent.com/73365/48083512-2ff3d900-e1aa-11e8-8168-91ccea389ee4.png">

Acceptance criteria:

- [ ] Ursus converts double hyphens (`--`) in the solr index to em dashes (`—`, U+2014):
<img width="272" alt="screen shot 2018-11-06 at 9 33 09 am" src="https://user-images.githubusercontent.com/73365/48083536-3f732200-e1aa-11e8-9dca-8d743d48a62a.png">

We could also consider spaces and en dashes, which results in slightly different line breaks:
<img width="272" alt="screen shot 2018-11-06 at 9 31 15 am" src="https://user-images.githubusercontent.com/73365/48083569-5c0f5a00-e1aa-11e8-941a-533155ac94d0.png">

**Comment by andrewbenedictwallace** [comment]
After running into some trickiness, I don't think this is worth the squeeze at this point. I can get various partial fixes to work for different parts of the site, but am having trouble getting them to work together. Also, testing is hard because the prior state of the solr index is affecting what shows up in the facet sidebar.

We might want to talk about converting the underlying data at some point (i.e., reviving https://github.com/UCLALibrary/californica/issues/316).

I'm provisionally tagging this "wontfix" and recommend removing from sprint.

**Comment by emcaulay** [comment]
For what it's worth, I think the double hyphen is more familiar / correct at this point. So, the only thing I care about is not having weird line wrapping.
