### ISSUE TITLE
Deploy a previous release via Jenkins

### ISSUE THREAD

**Issue by bess** [UCLALibrary/ursus#136]
As a devops professional, I want to be able to deploy the last known good release in case of a problem
- [ ] I can determine what the last known good release is
- [ ] I can deploy it via Jenkins

**Comment by hardyoyo** [comment]
https://github.com/UCLALibrary/ursus/releases lists all releases in decreasing order, one would assume the immediately previous release would be a "known good" release

**Comment by sgurnick** [comment]
Documentation relating to performing a capistrano rollback/revert: 
https://capistranorb.com/documentation/getting-started/rollbacks/

We should be cautious in using the `deploy:rollback` method - as stated in the documentation:

> In the majority of failed deployment situations, it probably makes more sense to revert the bad code and redeploy, rather than running deploy:rollback. Capistrano provides basic rollback support, but as each application and system handles rollbacks differently, it is up to the individual to test and validate that rollback behaves correctly for their use case. For example, capistrano-rails will run special tasks on rollback to fix the assets, but does nothing special with database migrations.

With this in mind, we'll probably want to develop our own process for performing a rollback/revert, based on the failure scenarios tested in #135.

**Comment by sgurnick** [comment]
Taking note of the information and scenarios in UCLALibrary/ursus#135, we already have the capability to deploy prior Californica/Ursus releases via the Jenkins process.

The caveat is no database changes can have occurred between the old and the new releases. 

As long as the difference between in the old and new release are code changes, then the jenkins deploy process will function as-expected.
