### ISSUE TITLE
Public: footer links

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#14]
- [x] Privacy Policy (http://www.library.ucla.edu/use/access-privileges/privacy-policy)
- [x] Giving to the Library (http://www.library.ucla.edu/give)

[Added 10/17 by Andy - moved from header]
- [x] Copyright and Collections (http://digital2.library.ucla.edu/copyright.html)
- [x] Contact (http://digital2.library.ucla.edu/contact.html)
 
Same as the footer for : http://digital2.library.ucla.edu

child of https://github.com/UCLALibrary/amalgamated-samvera/issues/129

**Comment by emcaulay** [comment]
@sshaferUCLA , Right now we have a link to the same page (copyright) in both the header and footer of the site. Please advise on where it should go. I'm leaving it in the header for now.

**Comment by andrewbenedictwallace** [comment]
@emcaulay Working on the header now and I think it's better to keep that simple and put most of the links here (as you suggest on the header ticket – I'll copy into the list above).

I'm going to move ahead w/ that, but it looks like an easy fix if we change our minds.
