### ISSUE TITLE
Revise design for "Give Us Feedback"

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/ursus#141]
As a user, I am happy that you are asking for "Feedback", but that little thing is always in my way.

## Acceptance criteria
- [ ] The "Give Us Feedback" is prominent, but does not block out other content elements.

**Comment by jendiamond** [comment]
I gave the FEEDBACK link the ability to close.
It will reappear when the page is refreshed at which point it can be closed again.

**Comment by jendiamond** [comment]
Inspiration / code snippets: https://codepen.io/senff/pen/fqmFo
