### ISSUE TITLE
Add environment variable for Google Tag Manager

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/ursus#154]
https://github.com/UCLALibrary/ursus/pull/149 gets the Google Analytics property name from an environment variable.

- [ ] GOOGLE_TAG_MGR_ID='GTM-T2SXV2' on at least ursus production – dev, stage, and test would also be ideal (I think we can configure GTM triggers to tell the difference – we'd normally just want production but might want to test things out on test/stage)

Required by 137

**Comment by sgurnick** [comment]
@andrewbenedictwallace : I can assist with this and thank for letting me about this env variable addition.

I need to get it added into the ansible template and deployed to the servers.

**Comment by sgurnick** [comment]
google tag manager id environment variable deployed to test, stage, prod ursus and californica web systems.
