### ISSUE TITLE
Public: Metadata in search results

### ISSUE THREAD

**Issue by bess** [UCLALibrary/ursus#16]
The following fields should appear in the Ursus search results (and any others should be removed):

- [x] Title
- [x] Description
- [x] ~~Normalized Date~~
- [x] Date.creation
- [x] Resource Type

- [x] Field names should display without solr suffixes

**Comment by hardyoyo** [comment]
related: UCLALibrary/californica#264

**Comment by hardyoyo** [comment]
![image](https://user-images.githubusercontent.com/611569/47456208-81a76700-d799-11e8-9d14-0dd66deabd73.png)

^^^ screenshot from my dev environment, good enough to close?

**Comment by emcaulay** [comment]
soooo I'm gonna ask @mark-dce about that ... he says usually the screenshot should come from one of the server environments instead of the local devs. Ideally this would come from our CD target, but we don't have one.
