### ISSUE TITLE
Public: Facets

### ISSUE THREAD

**Issue by bess** [UCLALibrary/ursus#18]
The following facets display for a search in Ursus:
- [ ] Subject
- [ ] Resource Type
- [ ] Genre
- [ ] Name (Subject) 
- [ ] Location
- [ ] Normalized Date
- [ ] ~Extent~
- [ ] Medium
- [ ] Dimensions
- [ ] Language

- [ ] All field names should be displayed without solr suffixes

**Comment by emcaulay** [comment]
consider removing extent?

**Comment by hardyoyo** [comment]
related: UCLALibrary/californica#267
