### ISSUE TITLE
Add a Collection Level description of LADNN to Ursus

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/ursus#183]
here is the text: The Los Angeles daily news was originally named the Illustrated Daily News by Cornelius Vanderbilt, Jr. when he started it in 1923. He copied the tabloid format of the New York daily news, although he rejected lurid and sensational journalism. In 1926 the paper went bankrupt and was taken over by Manchester Boddy, who changed the name to the Los Angeles daily news. He kept the tabloid format, with its heavy reliance on photographs. In 1954 it merged with the Mirror, the afternoon paper of the Los Angeles times, and became the Mirror-News. It lost reporters, columnists, and its more liberal flavor, and ceased publication in the early 1960s. The collection consists of 200,000 negatives of the Los Angeles Daily News.

**Comment by mark-dce** [comment]
This was handled by the other collections stories for ursus & californica.  We pull the collection description from californica, so if you want the text above, that the collection should be updated manually in californica (I'm assuming the text shown in the screenshot below is what comes directly from the DLCS export)

<img width="862" alt="image" src="https://user-images.githubusercontent.com/3064318/54700502-2340a380-4b01-11e9-97ac-0ecb6b84555c.png">
