### ISSUE TITLE
Revise homepage images

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#189]
**ACCEPTANCE**
- [ ] Create a wireframe of the desired new homepage
- [ ] Update the homepage to match the wireframe

**Comment by mark-dce** [comment]
I think this is a great strategy for the homepage.  One of the things some institutions do is set up a carousel of 4-8 images that cycle either on a timed schedule or each time the page re-loads.  It's a nice way to give a little variety to the homepage and highlight the breadth of the collection(s).

Refresh UCSB's homepage for an example: https://alexandria.ucsb.edu

**Comment by sshaferUCLA** [comment]
Great! Add the description for Los Angeles Daily News Negatives and you've got the intermediate homepage. See ticket 183 for text. 

Samvera Users Group asked me to mock up a wireframe very much like UCSB with a few SUG tweaks.

**Comment by sshaferUCLA** [comment]
Per workshop feedback, let's add the subject facet "Lifestyle". It will bring a happier concept to offset the more negative (but still interesting and loaded with pictures) concepts. Folks read a lot in to the placement of "Disaster" adjacent to "Government", so let's do the order:
People | Events | Disasters | Lifestyle | Government

**Comment by sshaferUCLA** [comment]
Can you include the picture citation at the bottom?  A few of the users I interviewed, liked the option to go directly to the picture.

**Comment by sshaferUCLA** [comment]
How do I know that the item being shown is from EVENTS category? 
People | **Events** | Disasters | Lifestyle | Government

**Comment by mark-dce** [comment]
Closing this ticket as it is superseded by the Carbon Five design recommendations.
