### ISSUE TITLE
Search bar escapes blue header on small screens

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/ursus#193]
This (good):
<img width="817" alt="screen shot 2018-12-10 at 11 56 11 am" src="https://user-images.githubusercontent.com/73365/49758315-7c33ac80-fc73-11e8-8792-a611360c0b84.png">

Becomes this (bad):
<img width="830" alt="screen shot 2018-12-10 at 11 56 24 am" src="https://user-images.githubusercontent.com/73365/49758324-82298d80-fc73-11e8-86b1-74e9e8ea670b.png">

**Comment by andrewbenedictwallace** [comment]
The initial version of this just used a fixed width for the search bar. It needs to auto-fill the available space. In bootstrap for this would be done with flex-* classes – not sure about bootstrap 3.

**Comment by andrewbenedictwallace** [comment]
Had trouble getting the css here to work – it can wait for input from Carbon 5.

**Comment by mark-dce** [comment]
There's going to be a new ticket about search bar placement per the Carbon Five V3 design recommendations, so I'm closing this ticket to avoid confusion and/or apparent duplication.
