### ISSUE TITLE
Add gallery and mosaic views to search result display

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#200]
**ACCEPTANCE**
- [ ] I can choose between gallery and list view to see my search results in ursus (like I can in californica)

*HINT:* See https://github.com/projectblacklight/blacklight-gallery and follow the instructions there...

**Comment by jendiamond** [comment]
I followed the directions.
When I started the local server I received this error:
<img width="832" alt="screen shot 2018-12-14 at 2 11 10 pm" src="https://user-images.githubusercontent.com/751697/50032692-4f9ccf00-ffaa-11e8-98b0-f35fa740346f.png">

**Comment by jendiamond** [comment]
#### $ `rails g blacklight_gallery:install`

```
Running via Spring preloader in process 87

      create  app/assets/stylesheets/blacklight_gallery.css.scss
      create  app/assets/javascripts/blacklight_gallery.js
      insert  app/controllers/catalog_controller.rb
      insert  app/models/solr_document.rb
    generate  openseadragon:install

Running via Spring preloader in process 94

      create  app/assets/stylesheets/openseadragon.css
      create  app/assets/javascripts/openseadragon.js
      insert  app/controllers/application_controller.rb
```

**Comment by jendiamond** [comment]
It is partially working out of the box but needs some additional work. 

<img width="1174" alt="screen shot 2018-12-17 at 9 44 28 am" src="https://user-images.githubusercontent.com/751697/50105102-9bd15480-01e0-11e9-80f5-d64b6dd2b7d7.png">
<img width="1261" alt="screen shot 2018-12-17 at 9 44 01 am" src="https://user-images.githubusercontent.com/751697/50105103-9bd15480-01e0-11e9-9d3b-116754f1c19d.png">
<img width="1237" alt="screen shot 2018-12-17 at 9 44 45 am" src="https://user-images.githubusercontent.com/751697/50105101-9bd15480-01e0-11e9-8a3a-5c650c8f344e.png">
<img width="622" alt="screen shot 2018-12-17 at 9 44 53 am" src="https://user-images.githubusercontent.com/751697/50105100-9b38be00-01e0-11e9-95bd-f245a52c767d.png">

**Comment by mark-dce** [comment]
Superseded by #275
