### ISSUE TITLE
Test out newer version of Blacklight

### ISSUE THREAD

**Issue by joshuago78** [UCLALibrary/ursus#212]
Per discussion during our Sprint 11 planning meeting, we agreed that we will limit this testing to just updating the Blacklight on Andy's docker instance and see what breaks. This is time boxed

**Comment by andrewbenedictwallace** [comment]
I know blacklight 7 upgrades from bootstrap 3 to 4, so we should check the rendering wherever we've written custom scss

**Comment by jendiamond** [comment]
That was cached. It completely DID NOT work. I am narrowing down why with the Blacklight contributors.

**Comment by jendiamond** [comment]
I made great progress with this.

The next step is to update node. I will need Andy's help with this.

```
RuntimeError in Catalog#index
Showing /ursus/app/views/catalog/_image_grid.html.erb where line #6 raised:

Autoprefixer doesn’t support Node v4.8.2. Update it.
Extracted source (around line #6):

4    <div class="thumbnail no-border">
5      <a href="/catalog?f%5Bsubject_sim%5D%5B%5D=People">
6        <img src="<%= image_url('chavez.jpg') %>" alt="Carlos Chávez, portrait" Style="border: 1px solid #ddd; width:100%"/>
7      </a>
8      <div class="caption">
9        <%= link_to_featured_work('Carlos Chávez, portrait', '13030/hb7k4007rb') %>
```

https://stackoverflow.com/questions/52708521/autoprefixer-doesn-t-support-node-v4-8-2-update-it

We may want to try to upgrade to Rails 5.2.1 and Ruby 2.5.1 while we are at it. :)

**Comment by jendiamond** [comment]
Stopped at updating node.

**Comment by jendiamond** [comment]
Worked with Justin Coyne to get Blacklight update locally.
Pushed the branch `update-BL' 1-22-19
