### ISSUE TITLE
Public: Display Lat & Long as combined value with label "Geographic Coordinates"

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/ursus#22]
As someone interested in geolocating an historic image on a current map using coordinates, I would like to se

We are storing Latitude and Longitude as separate values in the Californica. Please change Ursus to display the values together separated by a comma. With the label "Geographic coordinates"

**Comment by val99erie** [comment]
If you want to see this change in a californica or ursus environment, you would need to either create a new work with a latitude and longitude, or reindex an existing work.  Existing work records won't display the coordinates field until their solr index gets updated.
