### ISSUE TITLE
Cite this item contains a link to ursus-test

### ISSUE THREAD

**Issue by sshaferUCLA** [UCLALibrary/ursus#224]
Go to any item level record

Click on 'Cite this item'

The citation will contain a link to the item with ursus-test in the URL

**Comment by mark-dce** [comment]
@sshaferUCLA I think is has been fixed now.  Is it OK to close this ticket?

<img width="803" alt="image" src="https://user-images.githubusercontent.com/3064318/54700839-c1cd0480-4b01-11e9-8959-8e6c249bc225.png">

**Comment by sshaferUCLA** [comment]
OK to close this ticket

________________________________
