### ISSUE TITLE
Implement collections in ursus

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/ursus#228]
Once collections-level records have been implemented in californica, they need to show up in ursus. This work has been done as part of Samvera; we can largely copy that implementation into ursus.

Acceptance:
- [x] Californica's collection records are used to populate the current "collection name" field (or something functionally equivalent)
- [x] Collection-level records can be viewed, consisting of
  - [x] collection metadata
  - [ ] ~list of items in the collection~ (we're going to postpone this until further into the C5 UX design implementation)

child of https://github.com/UCLALibrary/californica/issues/385

requires https://github.com/UCLALibrary/californica/issues/395

**Comment by jendiamond** [comment]
### Does this mean something like this?

![Screen Shot 2019-03-14 at 6.02.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f76b7191a37ef112294f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19141c95df349e74c57a513316be3712431.png)

---

### This is what the collection lloks like when you click on the collection

![Screen Shot 2019-03-14 at 6.18.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f76b7191a37ef113234f5c5c5ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19141c95df349e74c57ad143663e3742431.png)

Collection: Cats
Items: [ ]

**Comment by jendiamond** [comment]
![Screen Shot 2019-03-15 at 8.06.10 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f66b7191a370f1122d4f5e5f5edd3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df349e74b57a0113763e3742431.png)

**Comment by mark-dce** [comment]
Collection-level records were already appearing in Ursus (if you looked them up by ID).  The outstanding issue was that they weren't showing up in search results or faceting which has been addressed in #255 - Include collection-level records in search results and #246 - Display collection membership in Collection facet.  

I'm closing this ticket since the necessary work was completed as part of #246 & #255
