### ISSUE TITLE
Set up dotenv for Ursus

### ISSUE THREAD

**Issue by little9** [UCLALibrary/ursus#23]
- [x] Ursus configuration details can be changed using `dotenv` settings

**Comment by bess** [comment]
Ursus is already using dotenv: https://github.com/UCLALibrary/ursus/blob/master/Gemfile#L8
https://github.com/UCLALibrary/ursus/blob/master/config/solr.yml#L6

If something else was meant by the creation of this ticket could we be more specific about the goal?
