### ISSUE TITLE
Update ursus to blacklight 7

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/ursus#236]
Acceptance criteria
- [ ] Ursus is running on blacklight 7
- [ ] all pages look like they did with blacklight 6
- [ ] review outstanding bug tickets, see which ones still occur and which ones we can close

see notes in #212

**Comment by jendiamond** [comment]
https://github.com/projectblacklight/blacklight/releases/tag/v7.0.0
https://github.com/projectblacklight/blacklight/releases/tag/v7.0.1

**Comment by mark-dce** [comment]
Just a call out that the Blacklight v7.0.0 upgrade instructions provide a link the the bootstrap 3-->4 upgrade guide which should also be reviewed as part of the work on this ticket.

**Comment by jendiamond** [comment]
Probably best to do this from dev, where we can let it fail and not interrupt everything else.

**Comment by emcaulay** [comment]
I'm wondering how this work is going.

**Comment by jendiamond** [comment]
Once we update to Blackllight 7 and Bootstrap 4 the side bar disappears
![Screen Shot 2019-03-05 at 5.38.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206454f66b7191a37df111234f5c565ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19141c95df34ae94e53a0113765e4712431.png)

rspec ./spec/features/search_results_spec.rb:43 # Search results page displays: title, description, date_created, resource_type, and photographer
rspec ./spec/features/search_results_spec.rb:54 # Search results page displays facetable fields as links
rspec ./spec/features/facet_by_date_spec.rb:29 # Search the catalog get correct search results
rspec ./spec/features/genre_display_spec.rb:18 # The genre field of the item display view lists each genre on its own line, as a link to a search for that genre
rspec ./spec/features/search_catalog_spec.rb:116 # Search the catalog verify facet links are present
rspec ./spec/features/facet_labels_spec.rb:27 # The facet sidebar displays expected facet labels
rspec ./spec/features/view_work_spec.rb:99 # View a Work displays line breaks between the values of certain fields
rspec ./spec/features/view_work_spec.rb:46 # View a Work displays the metadata
rspec ./spec/features/view_work_spec.rb:107 # View a Work only displays the tools we want to support
rspec ./spec/features/view_work_spec.rb:86 # View a Work displays facetable fields as links
rspec ./spec/features/view_work_spec.rb:79 # View a Work license it displays the creative commons text and logo when there is a cc license
