### ISSUE TITLE
docker: get images working in ursus development environment

### ISSUE THREAD

**Issue by andrewbenedictwallace** [UCLALibrary/ursus#239]
The ursus development environment comes with a pre-populated copy of the californica-test solr index. It should be including images from the californica-test instance of cantaloupe.

I think the issue is related to CORS and fixable with some rack middleware that sets the right http headers. It's also posible I've set IIIF_URL incorrectly.

Acceptance criteria:
- [ ] ~When developing locally, universal viewer shows images from the californica-test cantaloupe server~
- [ ] When running with `docker-compose-with-californica.yml`, universal viewer shows images from locally-running californica's built-in RIIIF server.

**Comment by val99erie** [comment]
@andrewbenedictwallace Here is some info that might help you:

```
Environment variables needed to use Hyrax's built-in RIIIF server to serve images.

In Californica, make sure you don't have the env variable set:

unset  IIIF_SERVER_URL
export IIIF_SERVER_URL

In Ursus, you need to point to Californica's IIIF path.  So, if your Californica is running on port 3000, it would be this path:

export IIIF_URL='http://localhost:3000/concern/works'
```

**Comment by val99erie** [comment]
@andrewbenedictwallace  I removed the requirement to point to an external cantaloupe in the development environment.  I don't think that's actually necessary.  The built-in riiif server should work just fine for the development environment.
