### ISSUE TITLE
Change the identifier to read ark:/ 

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/ursus#242]
<img width="609" alt="screen shot 2019-02-22 at 3 06 00 pm" src="https://user-images.githubusercontent.com/751697/53276409-b7ab1800-36b3-11e9-8366-391cfa7f0bd4.png">

**Comment by emcaulay** [comment]
Lisa moved this ticket inn progress because it sounded like at standup that Jen and Val were working on this and they are assigned to it.

**Comment by jendiamond** [comment]
This is a different piece that we hadn't started yet.

**Comment by mark-dce** [comment]
Superseded by UCLALibrary/californica#457 *Ensure items are imported with an 'ark:' prefix*  and UCLALibrary/californica#456- i.e. we're going to ensure that there is a separate ARK property and that they are always stored with the "ark:" prefix.

**Comment by emcaulay** [comment]
Should this ticket be marked as "wontdo"?
