### ISSUE TITLE
Implement V1 Search Design

### ISSUE THREAD

**Issue by nikkithayer** [UCLALibrary/ursus#251]
**ACCEPTANCE**
- [x] Search bar matches design
- [x] Does not include V2 "All Fields" button
- [x] Works on mobile

**DETAILS**
* Logo and assets are available here: https://projects.invisionapp.com/d/main#/console/16734276/350465648/inspect
* Colors and style guide are available here: 
https://projects.invisionapp.com/d/main#/console/16734276/350465650/inspect
* Full brand guidelines at:
http://brand.ucla.edu/identity/colors

**MOCK-UP**
![image](https://user-images.githubusercontent.com/1448246/53847469-b3a9b080-3f65-11e9-8a2c-042ff62f11a0.png)

**Comment by jendiamond** [comment]
![Screen Shot 2019-03-25 at 10.43.15 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456f66b7191a379ef0c2f52415e4bbc30254d58eeb9cb74fce36f34985619e8836e0a20c73919a5e98216ee54ba208a1d83bfbb8c4dc5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee24856a11b3164e077336e0a.png)

---
[Uploading Screen Shot 2019-03-25 at 10.45.48 AM.png...]
