### ISSUE TITLE
Implement Footer

### ISSUE THREAD

**Issue by nikkithayer** [UCLALibrary/ursus#252]
**ACCEPTANCE**
- [x] Footer matches design
- [x] Links go to intended destinations (currently on staging the "Giving to the Library" link doesn't work so we didn't add it here)

**DETAILS**
* Logo and assets are available here: https://projects.invisionapp.com/d/main#/console/16734276/350465647/inspect
* Colors and style guide are available here: 
https://projects.invisionapp.com/d/main#/console/16734276/350465650/inspect
* Full brand guidelines at:
http://brand.ucla.edu/identity/colors

**MOCK-UP**
![image](https://user-images.githubusercontent.com/1448246/53847544-06836800-3f66-11e9-97d9-ac47d8bf67df.png)

**Comment by jendiamond** [comment]
Web default
![Screen Shot 2019-03-21 at 5.01.22 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456f26b7191a37df1122a4f5d5d5ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df348e34c57ad153460e4742431.png)

Web Hover states
![Screen Shot 2019-03-21 at 5.01.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456f26b7191a37df1122a4f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19041c95df348e34c56a4113266e7722431.png)

Mobile default
![Screen Shot 2019-03-21 at 5.01.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456f26b7191a37df1122a4f5c565ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df348e34c56a4163461ef722431.png)

**Comment by emcaulay** [comment]
Great work, @jendiamond !
