### ISSUE TITLE
Implement Sidebar Facets

### ISSUE THREAD

**Issue by nikkithayer** [UCLALibrary/ursus#253]
**ACCEPTANCE**
- [x] Facets match color and shape of mocks below
- [x] Includes re-styling colors on Date picker
- [x] Copy changes from "Limit your search" to "Refine your search" and from "more »" to "See all **[quantity of results]** [facet name]" 
- [ ] Active filters are visible and can be removed from the query when the facet is collapsed

**DETAILS**
* Logo and assets are available here: https://projects.invisionapp.com/d/main#/console/16734276/350465644/inspect
* Colors and style guide are available here: 
https://projects.invisionapp.com/d/main#/console/16734276/350465650/inspect
* Full brand guidelines at:
http://brand.ucla.edu/identity/colors

**MOCK-UP**
![image](https://user-images.githubusercontent.com/1448246/53847758-c53f8800-3f66-11e9-8944-3911a7f053f6.png)

**Comment by mark-dce** [comment]
Merge with #282
