### ISSUE TITLE
Include collection-level records in search results

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#255]
### PR #[255]( https://github.com/UCLALibrary/ursus/compare/view-collections-in-search_255?expand=1)

---

**ACCEPTANCE**
When a collection record exists in Californica
- [x] It should appear in ursus search results

*NOTE:* for now search relevancy does not matter - the collection record can appear anywhere in the results as long as it's somewhere in the results

Californica Current Behavior
===================
https://californica-test.library.ucla.edu/catalog?utf8=✓&locale=en&search_field=all_fields&q=Thursday  

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/3064318/53898309-70028580-3ffd-11e9-9d2e-4ec86ccf9f8e.png">

Ursus Current Behavior
=================
https://ursus-test.library.ucla.edu/catalog?utf8=✓&search_field=all_fields&q=Thursday  

<img width="899" alt="image" src="https://user-images.githubusercontent.com/3064318/53898492-c8d21e00-3ffd-11e9-8b1a-420d8168128a.png">

Actual Collection Exists in Ursus
==============
https://ursus-test.library.ucla.edu/catalog/2801pg68r   

<img width="696" alt="image" src="https://user-images.githubusercontent.com/3064318/53898572-f15a1800-3ffd-11e9-934d-17aed55b178e.png">

**Comment by jendiamond** [comment]
![Screen Shot 2019-03-12 at 3.33.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f16b7191a37bf111284f5e565ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df349e44d54a0143463e6722431.png)

---
![Screen Shot 2019-03-13 at 11.24.59 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f06b7191a379ee0c2955415a47bc30254d58eeb9cb74fce36f34985619e8836e0a20c73919a5e98216ee54ba208a1d83bfbb8c4dc5fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ee34855a5163562ef70346e0a.png)
