### ISSUE TITLE
Show collection thumbnails in search results

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#256]
**STORY**
As a user when my search results include collections,   
I would like to see a unique thumbnail image with  each collection,   
so that I can more easily scan and remember search results.

**ACCEPTANCE**
When a collection exists in Californica and has a thumbnail set  
- [ ] The collections thumbnail is displayed in search results that include the collection

*HYPOTHESIS:* 
 https://github.com/UCLALibrary/californica/issues/429 does not block this,   
since there is a thumbnail in the collection data model.

**Comment by jendiamond** [comment]
If a thumbnail is selected for the collection it is viewable.
![Screen Shot 2019-03-14 at 3.50.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f76b7191a37bf1172b4f5d5f5ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df349e74d56ac143464ef732431.png)
