### ISSUE TITLE
Show collection banner on Collection view

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#257]
**STORY**
As a collection owner, when I've set a collection banner in the collection branding page, I would like that banner to display at the top of the collection show page in ursus, so that I can reinforce collection level branding.

**ACCEPTANCE**
When the collection has a banner set in californica
- [x] The collection show page in ursus displays the banner below the header
Styling (note: we'll be doing more styling as part of the Carbon Five recommendations, so for now we want something that just looks clean and not-broken)
- [x] The banner has a max height of 150px
- [x] The banner is centered below the header
- [x] The banner has a max width that matches the content margins below it

Californica Current Behavior
===================
https://californica-test.library.ucla.edu/collections/2801pg68r?locale=en  

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/3064318/53899771-937aff80-4000-11e9-869f-c17cd9aff998.png">

Ursus Current Behavior
===============
https://ursus-test.library.ucla.edu/catalog/2801pg68r

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/3064318/53899834-b6a5af00-4000-11e9-9793-9902549f80a6.png">

Ursus Desired Behavior
==============
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/3064318/53900371-09339b00-4002-11e9-9f55-2e4b2e76cd80.png">

**Comment by emcaulay** [comment]
I can't verify that this intended behavior is working. I think we should move this back to in progress, but that might be not a good workflow practice. I'm going to leave it to you, @little9  to decide!
