### ISSUE TITLE
Delete Blacklight saved searches

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/ursus#264]
- [ ] Add cron job to automatically delete any Blacklight saved searches so that the database doesn't fill up
https://github.com/UCLALibrary/californica/blob/a197c0714075a373a8a6fe61dc8617f48f7a976e/config/schedule.rb

**Comment by bess** [comment]
Superseded by https://github.com/UCLALibrary/amalgamated-samvera/issues/287
