### ISSUE TITLE
Ability to browse by resource type and location

### ISSUE THREAD

**Issue by sshaferUCLA** [UCLALibrary/ursus#266]

**Comment by sshaferUCLA** [comment]
As a researcher I want the ability from homepage to browse by resource type and location so that I can find pictures of Los Angeles

**Comment by mark-dce** [comment]
@sshaferUCLA - we believe that this can be done using the "Resource Type" and "Location" facets.  Can we close this ticket, or can you express more detailed steps about what appears not to be working.

**Comment by mark-dce** [comment]
Looks like we're good with existing features.
