### ISSUE TITLE
Add link to library homepage (from header)

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#268]
**STORY**
As a repository owner, I would like a link from the page header back to the main library homepage, so that I am consistent with UCLA practice on other sites *AND* so users can easily navigate to more library resources.

**DETAILS**
NOTE: we've chosen a side-by-side layout like this:
> **UCLA Library** | Digital Collections

instead of and over-under like this

> *UCLA Library*
> Digital Collections

Because the latter is less accessible because it doesn't provide click target that are as large and distinct.

**ACCEPTANCE**
- [x] Include a link to https://www.library.ucla.edu in the header right
- [x] The link should match the C5 design V1 - i.e. **UCLA Library** | Digital Collections (not the over under layout shown below) 
- [x] Use UCLA colors for hover 
- [ ] Use UCLA colors for visited

**DETAILS**
* Logo and assets are available here: https://projects.invisionapp.com/d/main#/console/16734276/350465645/inspect
* Colors and style guide are available here: 
https://projects.invisionapp.com/d/main#/console/16734276/350465650/inspect
* Full brand guidelines at:
http://brand.ucla.edu/identity/colors

**MOCK-UP**
![image](https://user-images.githubusercontent.com/1448246/53846043-4cd5c880-3f60-11e9-8600-965b426fb591.png)
![image](https://user-images.githubusercontent.com/1448246/53846823-4a28a280-3f63-11e9-9fd8-df337b804bab.png)

**Comment by emcaulay** [comment]
This doesn't look ready for release to me, but I might not understand where to look.

**Comment by emcaulay** [comment]
Ooo -- I just tested it! It works! Very exciting!
