### ISSUE TITLE
Implement an "About" Page

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#269]
**STORY**
As a repository user, I would like an easy way to find out more about the repository...

**ACCEPTANCE**
- [x] Use the "accordion" design from Carbon Five V3 recommendation for static pages
- [x] Add an accordion slot for "Mission" that has placeholder content from this page http://digital2.library.ucla.edu/mission.html
- [x] Add an accordion slot for "Copyright and Collections" that has placeholder content from this page http://digital2.library.ucla.edu/copyright.html

**DETAILS**
* Logo and assets are available here: https://projects.invisionapp.com/d/main#/console/16734276/350465645/inspect
* Colors and style guide are available here: 
https://projects.invisionapp.com/d/main#/console/16734276/350465650/inspect
* Full brand guidelines at:
http://brand.ucla.edu/identity/colors

**MOCK-UP**
See the InVision V3 About page mockup https://projects.invisionapp.com/d/main/default/#/console/16734276/350475123/preview

**Comment by jendiamond** [comment]
![Screen Shot 2019-03-22 at 5.56.29 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456f16b7191a37df1172d4f5d565ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19141c95df348e24d57ac173763e0722431.png)

View at https://ursus-test.library.ucla.edu/about
