### ISSUE TITLE
Include search breadcrumbs on results

### ISSUE THREAD

**Issue by sshaferUCLA** [UCLALibrary/ursus#271]

**Comment by sshaferUCLA** [comment]
As a researcher I want the ability from the search results page to see & interact with search breadcrumbs. 

Design
Search breadcrumbs displaying on the search results page should be
centrally located near each other whether they are produced from search terms, or a selection from any of the available search facets.
should not take too much visual screen real-estate

**Comment by tinuola** [comment]
Hi @sshaferUCLA , Can you add links to the related InVision mockup(s) to this ticket?

**Comment by little9** [comment]
@sshaferUCLA @tinuola If I remember the discussion in the ticket writing meeting before this sprint correctly, these weren't present in the mockups, but were something that was wanted.

There are already search breadcrumbs in ursus (after the recent Blacklight upgrade):
![Screenshot from 2019-04-02 15-02-40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589de7daddc0c81a00399ded/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f37f3dd5b168ee1736515d424aac53444d04bea6d37ef5f22e7a985959ee84395e70ce3440acb1d34abf01bb728d4682b0bd8f5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5df249e24856ad173e6be7647b.png)

**Comment by mark-dce** [comment]
@sshaferUCLA can you confirm if the current Ursus release has the breadcrumbs (see the screenshot above or a live view at https://ursus.library.ucla.edu/catalog?f%5Bgenre_sim%5D%5B%5D=news+photographs&f%5Blanguage_sim%5D%5B%5D=No+linguistic+content)

**Comment by sshaferUCLA** [comment]
I confirm there are breadcrumbs on production ursus.library.ucla.edu

**Comment by tinuola** [comment]
Hi @emcaulay ,
I see that though closed this has been (re)assigned to me. Is there something specific to do about the ticket--besides styling, which would be a separate ticket?
