### ISSUE TITLE
Update styling on "no results found" page

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#274]
**STORY**
As a user, I would like clear messaging when no results match, so that I understand how to get back to main search.

**ACCEPTANCE**
- [ ] Update the current "no results" page to match the V3 design
- [ ] Keep the "Start Over" button from the live site, but style it to match V3 design patterns

**DETAILS**
* Logo and assets are available here: https://projects.invisionapp.com/d/main#/console/16734276/350465645/inspect
* Colors and style guide are available here: 
https://projects.invisionapp.com/d/main#/console/16734276/350465650/inspect
* Full brand guidelines at:
http://brand.ucla.edu/identity/colors

**CURRENT**
<img width="769" alt="image" src="https://user-images.githubusercontent.com/3064318/54302477-ea4b8080-458e-11e9-89c3-79ff809e072d.png">

**MOCK-UP**
https://projects.invisionapp.com/d/main/default/#/console/16734276/350475115/preview

**Comment by jendiamond** [comment]
### MOCK-UP
![Screen Shot 2019-03-21 at 6.08.58 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456f26b7191a37ef112234f5a575ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19041c95df348e34c53ad163f64e4712431.png)
