### ISSUE TITLE
Add a grid view for search results

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#275]
**STORY**
As a user, I'd like a grid view of my search results, so that I can visually compare matches more easily.

**ACCEPTANCE**
When I'm viewing a search result list,
- [x] I can click buttons to switch between list view and grid view
- [x] Grid view results show a title with each image

**DETIALS**
See https://github.com/projectblacklight/blacklight-gallery
We'll need to confirm that Blacklight gallery is compatible with Blacklight 7

**Comment by jendiamond** [comment]
This cannot be achieved right now because of dependencies. 

The `blacklight-gallery was resolved to 0.0.1, which depends on blacklight version  (>= 5.0.0.pre4, < 6.0)`

```
Bundler could not find compatible versions for gem "blacklight":
  In snapshot (Gemfile.lock):
    blacklight (= 7.0.1)

  In Gemfile:
    blacklight (~> 7.0.1)

    blacklight-gallery was resolved to 0.0.1, which depends on
      blacklight (>= 5.0.0.pre4, < 6.0)

    blacklight_range_limit (~> 7.0.0) was resolved to 7.0.0, which depends on
      blacklight

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by jendiamond** [comment]
I send Justin Coyne an email. I have been in touch with him before about Blacklight 7 so it's not completely out of the blue for me to contact him I hope.

Hi Justin,
​
Are there any thoughts to updating the blacklight-gallery to work with Blacklight 7?
I just put an issue in the repo but I was wondering if you had any insights that I could relay to my team here at UCLA. :)
​
Jen

**Comment by mark-dce** [comment]
@jendiamond you might get a response more quickly by asking on the code4lib#blacklight channel or e-mailing the blacklight-development@googlegroups.com mailing list instead of asking Justin directly.

**Comment by mark-dce** [comment]
@little9 I'm re-opening this ticket because 
1) I don't see images in the gallery views
2) I'm seeing mortar and slideshow views which should probably be disabled (at least slide-show)
3) Field labels are overlapping field values in grid view
4) Columns are overlapping in mortar view

@tinuola is working on a detailed mock up, so the view doesn't have to be perfect, but I think we should at least be showing images.  Here's what I'm seeing in production:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/3064318/55045127-05d87180-4ffa-11e9-8bc7-078bdb9659e3.png">

**Comment by mark-dce** [comment]
I just saw #308 reporting the same issues as a bug, so I'll close this.
