### ISSUE TITLE
Fullscreen button missing in image viewer

### ISSUE THREAD

**Issue by billha** [UCLALibrary/ursus#278]
The fullscreen button disappeared from the image viewer. I think this may have occurred when we upgraded to Blacklight 7.

**ACCEPTANCE**
- [ ] Universal Viewer in Ursus displays a button that allows a user to use UV in full screen mode

<img width="721" alt="image" src="https://user-images.githubusercontent.com/3064318/54532025-c30cfe80-4954-11e9-8d0f-5a38c53d6576.png">

**Comment by andrewbenedictwallace** [comment]
Same problem and fix as https://github.com/UCLALibrary/amalgamated-samvera/issues/286 – we need to restore uv-config.json and get it to load again
