### ISSUE TITLE
Update homepage display of collections to C5 design (v1)

### ISSUE THREAD

**Issue by tinuola** [UCLALibrary/ursus#283]
**STORY**
As a user, I would like to be able to see on the homepage the first two available collections, descriptions about them, a preview of some of their content, and how many items they contain.

**ACCEPTANCE**
Update the current homepage to match the V1 design
- [ ] Section title ("Available Collections")
- [ ] Section introductory text (Confirm with Lisa)
- [ ] Collection title and description
- [ ] One mid-sized image to represent the collection
- [ ] Three thumbnail/preview images from the collection
- [ ] Asset count (Button?)

**DETAILS**
* Assets are available here: https://projects.invisionapp.com/d/main#/console/16734276/346995485/inspect
* Colors and style guide are available here: 
https://projects.invisionapp.com/d/main#/console/16734276/350465650/inspect
* Full brand guidelines at:
http://brand.ucla.edu/identity/colors

**CURRENT**
![current collection display on homepage](https://user-images.githubusercontent.com/24995224/54461513-fcadf180-4729-11e9-8729-b8000e507a93.png)

**MOCK-UP**
![v1-collections-display](https://user-images.githubusercontent.com/24995224/55434425-76c4df80-554c-11e9-9f48-a838d2533429.png)

https://projects.invisionapp.com/d/main#/console/16734276/346995485/preview

**Comment by mark-dce** [comment]
During Sprint 17 Planning, we discussed options and decided to accelerate finalizing design for a homepage reflecting many collections and diverse content.  See ticket #333 for more details.
