### ISSUE TITLE
# Update Search Results/List View design to C5 V3

### ISSUE THREAD

**Issue by tinuola** [UCLALibrary/ursus#284]
**STORY**
As a user, I would like to be able to see my search results displayed in a list view with the design updated to match Carbon 5's Version 3 design 

**ACCEPTANCE**
See Below
 - [x] Update current homepage to match layout in V3 design
 - [x] Update current homepage to match styling in V3 design
 - [x] Visible display controls
 - [x] Active "List View" option

**DETAILS**

Assets are available here: https://projects.invisionapp.com/d/main#/console/16734276/350475118/inspect
Colors and style guide are available here:
https://projects.invisionapp.com/d/main#/console/16734276/350465650/inspect
Full brand guidelines at:
http://brand.ucla.edu/identity/colors

**CURRENT**
![ursus-list-view](https://user-images.githubusercontent.com/24995224/54549335-15efb180-4967-11e9-9db4-3ab7ffeb001d.png)

**MOCK-UP**
https://projects.invisionapp.com/d/main#/console/16734276/350475118/preview

**Comment by jendiamond** [comment]
### MOCK-UP
![Screen Shot 2019-03-22 at 3.33.53 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456f16b7191a37bf111284f5a5c5ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19141c95df348e34451a41b3560e5702431.png)

**Comment by little9** [comment]
The above criteria are hard to understand. These are the actual changes needed
to be like the C5 design:

- [ ] There is a header that has a result count: like  3 Catalog Results in the 
- [ ]  Add labels to the view buttons
- [ ] Reduce the size of the title header  in the search results (number is the same size as well)
- [ ] Metadata field label are dark blue and bold
- [ ] Description has larger width

**Comment by tinuola** [comment]
@little9 I see what you mean. Future stories will be more explicit about actual changes. And I'll revisit other stories in the backlog and revise them as needed. Thanks!
