### ISSUE TITLE
Update pagination and display options to C5 - V3

### ISSUE THREAD

**Issue by tinuola** [UCLALibrary/ursus#286]
**STORY**
As a user, I would like to be able to see pagination and display options after a search returns results. I want to be able to choose how many results to see per page and choose how I want the results displayed. 

**ACCEPTANCE**
- [x] Pagination bar at the top of results page body
- [x] Pagination bar at the bottom of results page body
- [x] Display options bar at the top of results page body
- [x] Options available: Results per page, List View, Grid View
- [x] No "Map View" in display options

**DETAILS**
* Assets are available here: https://projects.invisionapp.com/d/main#/console/16734276/350475122/inspect
* Colors and style guide are available here: 
https://projects.invisionapp.com/d/main#/console/16734276/350465650/inspect
* Full brand guidelines at:
http://brand.ucla.edu/identity/colors

**CURRENT**
Top of results body:
![ursus-pagination-top](https://user-images.githubusercontent.com/24995224/54551190-d32fd880-496a-11e9-8da8-c9e390739626.png)
Bottom of results body:
![ursus-pagination-bottom](https://user-images.githubusercontent.com/24995224/54551198-d62ac900-496a-11e9-9dce-e5d4b04a405a.png)

**MOCK-UP**
https://projects.invisionapp.com/d/main#/console/16734276/350475122/preview

**Comment by jendiamond** [comment]
![Screen Shot 2019-04-02 at 1.20.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276454f16b7191a379f1102b4f5b575ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df34fe34e52a5103062e1742431.png)

---
![Screen Shot 2019-04-02 at 1.21.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276454f16b7191a379f1102a4f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df34fe34e52a5163562e6702431.png)

**Comment by jendiamond** [comment]
Removed acceptance criteria "Update current search results display/pagination styling to match C5 design (v3)" from this story. Will create a separate styling story/ticket.

**Comment by jendiamond** [comment]
https://github.com/projectblacklight/blacklight/wiki/Pagination

**Comment by jendiamond** [comment]
- [x] Pagination bar at the top of results page body
- [x] Display options bar at the top of results page body
- [x] Options available: Results per page, List View, Grid View
- [x] No "Map View" in display options

![Screen Shot 2019-04-05 at 5.13.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276454f66b7191a37df113284f5e585ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df34fe44d5ca21b3166ee732431.png)

---

- [x] Pagination bar at the bottom of results page body
![Screen Shot 2019-04-05 at 5.13.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276454f66b7191a37df113284f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df34fe44d5ca2103e67e17f2431.png)
