### ISSUE TITLE
Run Google Audit Scan

### ISSUE THREAD

**Issue by tinuola** [UCLALibrary/ursus#287]
**STORY**
As a developer/product owner, I want to be able to assess site performance on a sprint-to-sprint basis, compare it against a baseline, and share a report with others on the project.

**ACCEPTANCE**
- [x] Run Google Audit Tool on DLCS
  - [x] Homepage
  - [x] Search results list
  - [x] Item detail page
- [x] Run Google Audit Tool on Frontera
  - [x] Homepage
  - [x] Search results list
  - [x] Item detail page
- [x] Run Google Audit Tool on IDEP
  - [x] Homepage
  - [x] Search results list
  - [x] Item detail page
- [x] Run Google's Audit Tool on Ursus
  - [x] Homepage
  - [x] Search results list
  - [x] Item detail page
- [x] Share report

**DETAILS**
[Auditing Performance](https://developers.google.com/web/fundamentals/performance/audit/)
[Run Lighthouse in Chrome DevTools](https://developers.google.com/web/tools/lighthouse/#devtools)

**EXAMPLE**
i.e. run this test against each of the pages listed above and capture the results via screenshot or just copying the numbers
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/3064318/54659582-720a2100-4aa0-11e9-9cf1-45d20b0882b4.png">

**Comment by emcaulay** [comment]
This is a really cool ticket. I'm really interested in learning more about this. Thank you.

**Comment by mark-dce** [comment]
Preliminary results - detailed write-up forthcoming...


SITE | Performance | Accessibility | Best Practices | SEO
-- | -- | -- | -- | --
DLCS Lowest Overall | 69 | 55 | 64 | 50
Frontera Lowest Overall | 64 | 64 | 71 | 82
IDEP Lowset Overall | 39 | 89 ✅ | 57 | 90 ✅
Ursus Lowest Overall | 70 ✅ | 71 | 79 ✅ | 90 ✅
  |   |   |   |  
DLCS Homepage | 90 | 73 | 71 | 70
Frontera Homepage | 87 | 64 | 71 | 100 ✅
IDEP Homepage | 94 | 94 ✅ | 71 | 90
Ursus Homepage | 96 ✅ | 73 | 86 ✅ | 90
  |   |   |   |  
DLCS List Results | 62 | 55 | 64 | 60
Frontera List Results | 89 | 86 | 79 | 91 ✅
IDEP List Results | 39 | 89 ✅ | 57 | 90
Ursus List Results | 94 ✅ | 76 | 86 ✅ | 90
  |   |   |   |  
DLCS Item Detail | 69 | 64 | 71 | 50
Frontera Item Detail | 64 | 88 | 71 | 82
IDEP Item Detail | 58 | 94 ✅ | 71 | 90 ✅
Ursus Item Detail | 70 ✅ | 71 | 79 ✅ | 90 ✅
  |   |   |   |

**Comment by mark-dce** [comment]
Final Report:
2019-04-05 Website Comparative Metrics
https://docs.google.com/document/d/1YzByVSxJ64Mx0pK2tYsk52NZD7erKbwiGS5FBIzyhSE/edit#
