### ISSUE TITLE
Add line breaks between distinct subject headings

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/ursus#30]
As a user, it's hard to read a very long series of subject headings as a paragraph. I'd like to see each subject heading on it's own line

**Comment by little9** [comment]
@emcaulay I'll ping you to take a look at this when I can deploy to `ursus-dev`

**Comment by little9** [comment]
@emcaulay it's been deployed to https://ursus-dev.library.ucla.edu

**Comment by bess** [comment]
![subjects_paragraph_style.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5515e9ab52d65b2000638516/125516c66e82c728ace21e0d46fb8198298780bd9cd6af42b65cf78628562f4c3a10ba2775c7af6aaf50740b0a0c0abe4b4a5a16ffacdd2aa2be35218a555ab8d16d5e26c03416aab9870da313f871d51bdaebe5c01982fa3737e68d854e3b1d0c1f80fb5d32a7994ccf4abb.png)

**Comment by bess** [comment]
@little9 I don't think this is fixed. See screenshot from current (v0.0.2) ursus-dev pasted above. I think Lisa is talking about the metadata display (is that right, @emcaulay?) and your PR is talking about facets (which *also* needed fixing, of course).
