### ISSUE TITLE
Revise C5 Masthead design (V1)

### ISSUE THREAD

**Issue by tinuola** [UCLALibrary/ursus#315]
**STORY**
As a UX Designer, I would like to show project members an alternate view of the Ursus landing page masthead. The initial design proposed by Carbon Five obstructs the Powell Library image. 

A suggested alternative is to use the mid-page banner designed in V3 (see below) until the number of collections increases and we move into implementing the V3 design/masthead that's more collection-focused.

**ACCEPTANCE**
Update C5 Masthead design comp (V1): 
- [ ] Make sure that Powell Library facade is fully visible
- [ ] Display a Welcome Message, Description (and Call-to-Action?)
- [ ] Create a comp for mobile responsiveness
- [ ] Review with SUG and/or project team
- [ ] Update implementation ticket for developers to work on

<br>

Current C5 V1 Masthead:
https://projects.invisionapp.com/d/main#/console/16734276/346995485/preview
![C5-Masthead-V1](https://user-images.githubusercontent.com/24995224/55106549-7def7780-508c-11e9-860b-3a54a79c6cc8.png)

<br>

Current C5 V3 [Mid-page] Banner:
https://projects.invisionapp.com/d/main#/console/16734276/350475135/preview
![C5-Banner-v3](https://user-images.githubusercontent.com/24995224/55106580-95c6fb80-508c-11e9-9e8d-ecdad593f35d.png)

**Comment by mark-dce** [comment]
We're going to focus on V3 or multi-collection homepage since we will anticipate having 8+ collections in the repository within the next few sprints.
