### ISSUE TITLE
Implement C5 Masthead design (V1)

### ISSUE THREAD

**Issue by tinuola** [UCLALibrary/ursus#320]
**STORY**
As a user, when I visit the homepage I would like to be able to see a header-banner that introduces the Digital Library and includes a short descriptive text.

Dependent on #315 (Revise C5 Masthead design (V1))

**ACCEPTANCE**
- [ ] Clear, unobstructed image of Powell Library
- [ ] Header text "Welcome to the UCLA Digital Library Collection"
- [ ] Descriptive text about UCLA Digital Library
- [ ] CTA
- [ ] On mobile, the order of appearance is changed to:
  + [ ] Search bar?
  + [ ] Title banner
  + [ ] Image banner 
  + [ ] Text banner

Requires #315

**Comment by mark-dce** [comment]
We're going to focus on V3 or multi-collection homepage since we will anticipate having 8+ collections in the repository within the next few sprints.
