### ISSUE TITLE
Implement revised search results grid view

### ISSUE THREAD

**Issue by tinuola** [UCLALibrary/ursus#325]
**STORY**
As a user, I want to be able to see my search results displayed in a grid view with only item titles displayed.

Connected to #289 (Revise C5 comp for search results Grid View metadata)
Required by #326

**ACCEPTANCE**
- [ ] Display only one metadata: "Title"
- [ ] Truncate long titles to display the first three lines
  + _Approximate character count: 90 - 100?_

**Preview**
**Note: This is NOT a styling ticket.**
<br>

![grid-view-title-only](https://user-images.githubusercontent.com/24995224/55982969-dc9d1f80-5c4e-11e9-8cc6-ff802d324502.jpg)

**Comment by mark-dce** [comment]
@sshaferUCLA can you take a look and let Tinu know if the prototype looks good?

**Comment by jendiamond** [comment]
https://github.com/projectblacklight/blacklight-gallery/wiki
