### ISSUE TITLE
Apply C5 styling to single item view / show page

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#330]
**ACCEPTANCE**
- [x] Labels & Values use the fonts and colors specified in the design recommendations
- [x] Linked values use the specified colors and styling
- [x] Labels are shown on the line above the value
- [x] Labels and values are left-aligned

NOTE: this is only about styling and left-aligning all metadata.  Creating a sidebar for contextual metadata is handled in a separate story #331

**MOCKUP**
![image](https://user-images.githubusercontent.com/3064318/55495098-c87b7180-5601-11e9-920f-aa42f638b0ef.png)

**Comment by jendiamond** [comment]
https://github.com/UCLALibrary/ursus/pull/316/files

**Comment by jendiamond** [comment]
![Screen Shot 2019-04-09 at 5.01.26 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276454fa6b7191a37df1122a4f5d595ecc3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a29941c95df34fe94851a11a3165e4702431.png)
