### ISSUE TITLE
Remove mortar and slide-show from search results view options

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#332]
**ACCEPTANCE**
When I search for one or more items in ursus
- [x] I can view them as a list or gallery view
- [x] I do not have options to view them as a mortar or slideshow view

**MOCKUP**
![image](https://user-images.githubusercontent.com/3064318/55495598-e2698400-5602-11e9-8555-9a88f4ea223d.png)

**Comment by little9** [comment]
This is already the case on ursus, ursus-dev, and ursus-test:

![image](https://user-images.githubusercontent.com/4324761/55504880-72192d80-5617-11e9-8757-b26eb0953267.png)
