### ISSUE TITLE
Update homepage for several collections

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#335]
**STORY**
Since we're beginning to be able to more rapidly add new collections, we'd like to make minor changes to the homepage that would allow it to stay in place until design of a multi-collection, diverse-works design is complete (see #333)

**ACCEPTANCE**
- [x] The reference to "Los Angeles Daily News Negatives" on the homepage are removed
- [x] Add a paragraph describing the website

**Comment by jendiamond** [comment]
![Screen Shot 2019-04-04 at 9.40.49 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77276454f76b7191a371f1162b4f5b565edd3c4a4356bcbbd671f3e57862804e0ebfd2380b75c23518fdb88b4eea01ba21d9498cb1ba8b49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df34fe24453a4153560ee752431.png)

**Comment by jendiamond** [comment]
Digital Collections Blurb
(for use on the homepage)

Draft 1
The UCLA Library Digital Collections includes rare and unique digital materials developed by the UCLA Library to support education, research, service, and creative expression. This website is our new interface for discovery and engagement of these collections. 

https://docs.google.com/document/d/1ZksL0zCIRxIPAKGzjIhbk5aGeEKTaswqGeu1Qh1qeUg/edit

branch `update-home-page-copy`

**Comment by jendiamond** [comment]
![IMG_20190408_095724938.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5615719ec6cad148008cc8ae/125516c66e82c728ace21e0d46c1b9bd1cd0d3f8d6b9eb13fc62a0cd7c1175277057fb693cc7f33ab0487e021b4d44be440a5c11a8f88d23afe73c79db090bedd03f597dc13b10a9aa9e0dfd50e474d412dcfce9c85ecafa3f25ed8a8a4a3a19011a81f85a32a89d5985.jpg)
