### ISSUE TITLE
Give Bill permissions on Jenkins

### ISSUE THREAD

**Issue by jendiamond** [UCLALibrary/ursus#338]
Bill is learning how to be the release manager so he needs permission in Jenkins so he can deploy.

**Comment by croft103** [comment]
Bill's account has been setup on the jenkins server (https://jenkins-devsupport.library.ucla.edu). Remember you must be on our network or connect through the UCLA VPN. Slack me @billha when you are ready to set a password on the server.

**Comment by billha** [comment]
Registered with a strong 15 char password. All good.
