### ISSUE TITLE
Public: Display thumbnails in search results and show view

### ISSUE THREAD

**Issue by mark-dce** [UCLALibrary/ursus#39]
- [ ] Thumbnails generated in Californica are seen in the Ursus show view 
- [ ] Thumbnails generated in Californica are seen in the Ursus search results view

**Comment by little9** [comment]
- [ ] Thumbnails generated in Californica are seen in the Ursus show view 
- [ ] Thumbnails generated in Californica are seen in the Ursus show view 
![image](https://user-images.githubusercontent.com/4324761/47309333-bbda0280-d5f9-11e8-9a1c-fad1b46562ee.png)

Right now, the links to to the derivatives in californica are present on the page, but they need to 
have the correct URL appended to them. 

There could be an ENV variable that sets the californica base URL, which is appended to the image links in Ursus via the `catalog_controller`.
