### ISSUE TITLE
Public: Do NOT use rightsstatements.org

### ISSUE THREAD

**Issue by emcaulay** [UCLALibrary/ursus#46]
Political issue at UCLA Library at the moment. Lisa does not want to stir the pot.

Replaced by californica/#284

**Comment by bess** [comment]
@emcaulay Would you please provide some acceptance criteria for this bug? Do you want us to re-ingest all the data with different values? Or should we just not link to rightsstatements.org? Or is there some other acceptable way to address this? Thanks!

**Comment by emcaulay** [comment]
@bess -- good questions -- thanks. I will add acceptance criteria into the description above.
