### ISSUE TITLE
Public: Display correct names for metadata fields

### ISSUE THREAD

**Issue by little9** [UCLALibrary/ursus#47]
- [ ] None of the metadata fields have `_tesim` or `_sim` in the display name. 

The proper display names need to be set in the locale file:
https://github.com/UCLALibrary/ursus/blob/master/config/locales/blacklight.en.yml

**Comment by mark-dce** [comment]
Closing this in favor of each of the respective views:
#16 - search results
#17 - single item show view
#18 - Facet labels
