### ISSUE TITLE
Public: Photographer should be a facet link

### ISSUE THREAD

**Issue by bess** [UCLALibrary/ursus#66]
- [ ] A Photographer facet exists on Californica
- [ ] When I click on a Photographer  it should show me all other records with that photographer

**Comment by hardyoyo** [comment]
Via Anarchivist in the Code4Lib Blacklight channel:

You'd do this through your `CatalogController`, with the `link_to_search` parameter.

except...that that's deprecated in BL7. doh.

here you go: https://github.com/projectblacklight/blacklight/wiki/Blacklight-configuration#linking-a-value-to-a-facet-search

**Comment by hardyoyo** [comment]
Photographer does not appear to be a configured facet at the moment.
