### ISSUE TITLE
Public: Implement a date slider

### ISSUE THREAD

**Issue by bess** [UCLALibrary/ursus#69]
Instead of a "normalized date" facet, implement a Blacklight date slider so I can select a range of dates

- [x] The "Normalized Date" facet has been removed
- [x] It has been replaced by a date slider with the heading "Date"

Timebox this to one day of work. If the date slider doesn't work with the latest version of Blacklight, report back and stop working on this.

**Comment by hardyoyo** [comment]
discussion in Slack starts here: https://uclalibrary.slack.com/archives/CA5QYDKTM/p1540589401013700

**Comment by hardyoyo** [comment]
gist of the above-linked discussion is: the NormalizedDate field has values for year which can be utilized to build a year index. A date slider should use this computed index. There are also some values of NormalizedDate which are ranges, like `1941/1945` such ranges need to populate the year index with one value per year within the range (e.g. `1941`, `1942`, `1943`, `1944`, `1945')
