### ISSUE TITLE
Public: configure the "cite" link

### ISSUE THREAD

**Issue by bess** [UCLALibrary/ursus#73]
- [ ] When I click the "Cite" link on a show page in Ursus, I should get a formatted bibliographic entry 

![ursus-73](https://user-images.githubusercontent.com/3064318/48150300-dfe94500-e283-11e8-89cb-f7b3d370820e.png)

Depends on #125

**Comment by sshaferUCLA** [comment]
See 125

**Comment by emcaulay** [comment]
Here is a possible "algorithm". The SUG group voted for a formatted citation, but didn't get specific enough to provide examples for each citation style, so we'll start with something generic:

Here's the guidebook for developers to review: 

Curly brackets {} indicate data to be extracted from Samvera, value inside square brackets is the field name from Samvera.

indicates system to generate+
All other characters are literals.
{title}. [still image]. {collection name}. UCLA Library Distinctive Digital Collections. {persistent URL here} (web accessed +DD MONTH YYYY+)

Please advise if this is sufficient to go forward.

**Comment by hardyoyo** [comment]
everything above is doable, except "persistent URL here", I don't believe we have such a thing?

**Comment by emcaulay** [comment]
We've debated this topic of persistent URL, and there are multiple definitions. For now, please move forward with a revision of "CURRENT" url. I will revise my description above.

**Comment by andrewbenedictwallace** [comment]
For example:

Hollywood Committee for the First Amendment members disembarking plane in Los Angeles, Calif., 1947. [still image]. LA Daily News Negatives. UCLA Library Distinctive Digital Collections. https://ursus.library.ucla.edu/ark:/21198/zz0002nqfj (web accessed 05 December 2018)

???

**Comment by emcaulay** [comment]
Looks great to me!

**Comment by emcaulay** [comment]
@sshaferUCLA , you can review as well

**Comment by jendiamond** [comment]
I am working on this issue. Here are my notes:
https://gist.github.com/jendiamond/a985841b454630827577762d0498f8c5

**Comment by hardyoyo** [comment]
I've been out of the loop for the past few weeks, however, unless something has changed, the link in that citation will not work. Are we OK with that?

**Comment by jendiamond** [comment]
https://github.com/UCLALibrary/ursus/pull/194
