### ISSUE TITLE
Public: Accessibility audit of Ursus

### ISSUE THREAD

**Issue by bess** [UCLALibrary/ursus#76]
- [x] Commission an accessibility audit 
- [x] Report back and make tickets for anything we want to address

**Comment by sshaferUCLA** [comment]
WAVE accessibility testing tool report: http://wave.webaim.org/report#/https://ursus-stage.library.ucla.edu/

-[ ] Provide the correct alt text for the following two images. Use the title image. It should not be "Lights".
 `<a href="/catalog?f%5Bsubject_sim%5D%5B%5D=Disaster">
        <img src="https://ursus-stage.library.ucla.edu/assets/tombstone-51563fed55a97a9a79f8a8d607b0d6f2046430970aa62564893ecf25b3c5134b.jpg" alt="Lights" style="border: 1px solid #ddd; width:100%"/>
      </a>`
and 
` <a href="/catalog?f%5Bsubject_sim%5D%5B%5D=Government">
        <img src="https://ursus-stage.library.ucla.edu/assets/primary-3397b649418c888c7ff4d2f41b89c36037d8e549ccdba007e9cf0dc4a18ffe0e.jpg" alt="Lights" style="border: 1px solid #ddd; width:100%"/>
      </a>
      <div class="caption">
        <a href="/catalog/mp48sc77c">Corridor filled with men and women tabulating ballots for California primary election in Los Angeles, Calif., 1954</a>`

- [ ] Ensure the element referenced in the aria-labelledby or aria-describedby attribute value is present within the page and presents a proper label or description.
There is a broken aria reference. An aria-labelledby or aria-describedby reference exists, but the target for the reference does not exist.
`<div id="ajax-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal menu" aria-hidden="true">`


- [ ] Give the plugin content an informative name
 Alert 1:  An unidentified plugin is present  which leads to the content of a svg file with the title = "Asset 21".   
`<object data="https://ursus-stage.library.ucla.edu/assets/logo2-eb65eb4b432d503f6a4a3a365edbf301e3e29e1be6949ec30d80e91fa61b7229.svg" type="image/svg+xml">UCLA Library</object>`

**Comment by sshaferUCLA** [comment]
See Waffle 206
